package in.co.bel.ims.initial.entity;
// Generated 29-Oct-2022, 10:12:15 am by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.id.enhanced.SequenceStyleGenerator;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * AllowedMachines generated by hbm2java
 */
@Entity
@Table(name = "allowed_machines", schema = "tdms")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class AllowedMachines implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private ImsUser imsUser;
	private String ipAddress;
	private Boolean deleted;

	public AllowedMachines() {
	}

	public AllowedMachines(int id) {
		this.id = id;
	}

	public AllowedMachines(int id, ImsUser imsUser, String ipAddress, Boolean deleted) {
		this.id = id;
		this.imsUser = imsUser;
		this.ipAddress = ipAddress;
		this.deleted = deleted;
	}

	@Id
	@GenericGenerator(name = "sequencePerEntityGenerator", strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator", parameters = {
			@Parameter(name = "prefer_sequence_per_entity", value = "true"),
			@Parameter(name = "initial_value", value = "1"),
			@Parameter(name = SequenceStyleGenerator.INCREMENT_PARAM, value = "1") })
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ims_user_id")
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"}) 
	public ImsUser getImsUser() {
		return this.imsUser;
	}

	public void setImsUser(ImsUser imsUser) {
		this.imsUser = imsUser;
	}

	@Column(name = "ip_address", length = 50)
	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	@Column(name = "deleted")
	public Boolean getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

}
