package in.co.bel.ims.initial.entity;
// Generated 24-Nov-2022, 8:28:12 am by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.id.enhanced.SequenceStyleGenerator;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * ApplicationHits generated by hbm2java
 */
@Entity
@Table(name = "application_hits", schema = "tdms")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class ApplicationHits implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Date date;
	private Integer hitsCount;
	private boolean deleted;

	public ApplicationHits() {
	}

	public ApplicationHits(int id) {
		this.id = id;
	}

	public ApplicationHits(int id, Date date, Integer hitsCount) {
		this.id = id;
		this.date = date;
		this.hitsCount = hitsCount;
	}

	@Id
	@GenericGenerator(name = "sequencePerEntityGenerator", strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator", parameters = {
			@Parameter(name = "prefer_sequence_per_entity", value = "true"),
			@Parameter(name = "initial_value", value = "1"),
			@Parameter(name = SequenceStyleGenerator.INCREMENT_PARAM, value = "1") })
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "sequencePerEntityGenerator")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 13)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "hits_count")
	public Integer getHitsCount() {
		return this.hitsCount;
	}

	public void setHitsCount(Integer hitsCount) {
		this.hitsCount = hitsCount;
	}
	
	@Column(name = "deleted", nullable = false)
	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) { 
	 this.deleted = deleted;
		
	}

}
