package in.co.bel.ims.initial.entity;
// Generated 07-Oct-2022, 2:06:07 pm by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.id.enhanced.SequenceStyleGenerator;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Captcha generated by hbm2java
 */
@Entity
@Table(name = "captcha", schema = "tdms")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Captcha implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private String value;
	private Boolean valid;
	private boolean deleted;

	public Captcha() {
	}

	public Captcha(int id) {
		this.id = id;
	}

	public Captcha(int id, String value, Boolean valid) {
		this.id = id;
		this.value = value;
		this.valid = valid;
	}

	@Id
	@GenericGenerator(name = "sequencePerEntityGenerator", strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator", parameters = {
			@Parameter(name = "prefer_sequence_per_entity", value = "true"),
			@Parameter(name = "initial_value", value = "1"),
			@Parameter(name = SequenceStyleGenerator.INCREMENT_PARAM, value = "1") })
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "sequencePerEntityGenerator")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "value", length = 10)
	@Size(max=10, message="It should not be more than 10 characters")
	@Pattern(regexp = "[a-zA-Z0-9\\s+-]*", message = "Must not contain special characters")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "valid")
	public Boolean getValid() {
		return this.valid;
	}

	public void setValid(Boolean valid) {
		this.valid = valid;
	}
	
	@Column(name = "deleted", nullable = false)
	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) { 
	 this.deleted = deleted;
		
	}

}
