package in.co.bel.ims.initial.entity;
// Generated 20-Sep-2022, 3:54:24 pm by Hibernate Tools 4.3.5.Final

import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.id.enhanced.SequenceStyleGenerator;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Enclosure generated by hbm2java
 */
@Entity
@Table(name = "enclosure", schema = "mdms")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Enclosure implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private Integer createdBy;
	private LocalDateTime createdTimestamp;
	private boolean deleted;
	private EnclosureGroup enclosureGroup;
	private Integer maxCapacity;
	private Integer modifiedBy;
	private LocalDateTime modifiedTimestamp;
	private String name;
	private String remarks;
	@JsonIgnore
	private Set<EnclosurePassTypeMapping> enclosurePassTypeMappings = new HashSet<EnclosurePassTypeMapping>(0);
	@JsonIgnore
	private Set<ScanningOfficer> scanningOfficers = new HashSet<ScanningOfficer>(0);
	@JsonIgnore
	private Set<EnclosureCplMapping> enclosureCplMappings = new HashSet<EnclosureCplMapping>(0);
	@JsonIgnore
	private Set<Pass> passes = new HashSet<Pass>(0);
	@JsonIgnore
	private Set<InvitationOfficer> invitationOfficers = new HashSet<InvitationOfficer>(0);

	public Enclosure() {
	}

	public Enclosure(int id) {
		this.id = id;
		
	}

	public Enclosure(int id, EnclosureGroup enclosureGroup, Integer createdBy, LocalDateTime createdTimestamp, boolean deleted,
			Integer maxCapacity, Integer modifiedBy, LocalDateTime modifiedTimestamp, String name,
			String remarks, Set<EnclosurePassTypeMapping> enclosurePassTypeMappings,
			Set<InvitationOfficer> invitationOfficers, Set<ScanningOfficer> scanningOfficers,
			Set<EnclosureCplMapping> enclosureCplMappings, Set<Pass> passes) {
		this.id = id;
		this.enclosureGroup = enclosureGroup;
		this.createdBy = createdBy;
		this.createdTimestamp = createdTimestamp;
		this.deleted = deleted;
		this.maxCapacity = maxCapacity;
		this.modifiedBy = modifiedBy;
		this.modifiedTimestamp = modifiedTimestamp;
		this.name = name;
		this.remarks = remarks;
		this.enclosurePassTypeMappings = enclosurePassTypeMappings;
		this.invitationOfficers = invitationOfficers;
		this.scanningOfficers = scanningOfficers;
		this.enclosureCplMappings = enclosureCplMappings;
		this.passes = passes;
	}

	@Id
	@GenericGenerator(name = "sequencePerEntityGenerator", strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator", parameters = {
			@Parameter(name = "prefer_sequence_per_entity", value = "true"),
			@Parameter(name = "initial_value", value = "1"),
			@Parameter(name = SequenceStyleGenerator.INCREMENT_PARAM, value = "1") })
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "sequencePerEntityGenerator")

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "created_by")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	
	@Column(name = "created_timestamp", length = 29)
	public LocalDateTime getCreatedTimestamp() {
		return this.createdTimestamp;
	}

	public void setCreatedTimestamp(LocalDateTime createdTimestamp) {
		this.createdTimestamp = createdTimestamp;
	}

	@Column(name = "deleted", nullable = false)
	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) { 	 this.deleted = deleted;
		
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "enclosure_group_id")
	@NotNull
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"}) 
	public EnclosureGroup getEnclosureGroup() {
		return this.enclosureGroup;
	}

	public void setEnclosureGroup(EnclosureGroup enclosureGroup) {
		this.enclosureGroup = enclosureGroup;
	}

	@Column(name = "max_capacity")
	@NotNull
	public Integer getMaxCapacity() {
		return this.maxCapacity;
	}

	public void setMaxCapacity(Integer maxCapacity) {
		this.maxCapacity = maxCapacity;
	}

	@Column(name = "modified_by")
	public Integer getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Integer modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	
	@Column(name = "modified_timestamp", length = 29)
	public LocalDateTime getModifiedTimestamp() {
		return this.modifiedTimestamp;
	}

	public void setModifiedTimestamp(LocalDateTime modifiedTimestamp) {
		this.modifiedTimestamp = modifiedTimestamp;
	}

	@Column(name = "name", length = 200)
	@Size(max=200, message="It should not be more than 200 characters")
	@NotBlank
	@Pattern(regexp = "[a-zA-Z0-9\\s.,()&]*", message = "Must not contain special characters")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "remarks", length = 500)
	@Size(max=500, message="It should not be more than 500 characters")
	@NotBlank
	@Pattern(regexp = "[a-zA-Z0-9\\s.'@%&/,()#-]*", message = "Must not contain special characters")
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "enclosure")
	public Set<EnclosurePassTypeMapping> getEnclosurePassTypeMappings() {
		return this.enclosurePassTypeMappings;
	}

	public void setEnclosurePassTypeMappings(Set<EnclosurePassTypeMapping> enclosurePassTypeMappings) {
		this.enclosurePassTypeMappings = enclosurePassTypeMappings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "enclosure")
	public Set<ScanningOfficer> getScanningOfficers() {
		return this.scanningOfficers;
	}

	public void setScanningOfficers(Set<ScanningOfficer> scanningOfficers) {
		this.scanningOfficers = scanningOfficers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "enclosure")
	public Set<EnclosureCplMapping> getEnclosureCplMappings() {
		return this.enclosureCplMappings;
	}

	public void setEnclosureCplMappings(Set<EnclosureCplMapping> enclosureCplMappings) {
		this.enclosureCplMappings = enclosureCplMappings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "enclosure")
	public Set<Pass> getPasses() {
		return this.passes;
	}

	public void setPasses(Set<Pass> passes) {
		this.passes = passes;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "enclosure")
	public Set<InvitationOfficer> getInvitationOfficers() {
		return this.invitationOfficers;
	}

	public void setInvitationOfficers(Set<InvitationOfficer> invitationOfficers) {
		this.invitationOfficers = invitationOfficers;
	}

}
