package in.co.bel.ims.initial.entity;
// Generated 23-Nov-2022, 6:10:13 pm by Hibernate Tools 4.3.5.Final

import java.time.LocalDate;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.id.enhanced.SequenceStyleGenerator;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * PassDayLimit generated by hbm2java
 */
@Entity
@Table(name = "pass_day_limit", schema = "tdms")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class PassDayLimit implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Event event;
	private LocalDate date;
	private Boolean deleted = false;
	private Date createdTimestamp;
	private Date modifiedTimestamp;
	@JsonIgnore
	private Set<PassDayLimitCategory> passDayLimitCategories = new HashSet<PassDayLimitCategory>(0);

	public PassDayLimit() {
	}

	public PassDayLimit(int id) {
		this.id = id;
	}

	public PassDayLimit(int id, Event event, LocalDate date, Boolean deleted, Date createdTimestamp, Date modifiedTimestamp,
			Set<PassDayLimitCategory> passDayLimitCategories) {
		this.id = id;
		this.event = event;
		this.date = date;
		this.deleted = deleted;
		this.createdTimestamp = createdTimestamp;
		this.modifiedTimestamp = modifiedTimestamp;
		this.passDayLimitCategories = passDayLimitCategories;
	}

	@Id
	@GenericGenerator(name = "sequencePerEntityGenerator", strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator", parameters = {
			@Parameter(name = "prefer_sequence_per_entity", value = "true"),
			@Parameter(name = "initial_value", value = "1"),
			@Parameter(name = SequenceStyleGenerator.INCREMENT_PARAM, value = "1") })
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "sequencePerEntityGenerator")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "event_id")
	@NotNull
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	@Column(name = "date", length = 13)
	public LocalDate getDate() {
		return this.date;
	}

	public void setDate(LocalDate date) {
		this.date = date;
	}

	@Column(name = "deleted")
	public Boolean getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	@Column(name = "created_timestamp", length = 29)
	public Date getCreatedTimestamp() {
		return this.createdTimestamp;
	}

	public void setCreatedTimestamp(Date createdTimestamp) {
		this.createdTimestamp = createdTimestamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_timestamp", length = 29)
	public Date getModifiedTimestamp() {
		return this.modifiedTimestamp;
	}

	public void setModifiedTimestamp(Date modifiedTimestamp) {
		this.modifiedTimestamp = modifiedTimestamp;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "passDayLimit")
	public Set<PassDayLimitCategory> getPassDayLimitCategories() {
		return this.passDayLimitCategories;
	}

	public void setPassDayLimitCategories(Set<PassDayLimitCategory> passDayLimitCategories) {
		this.passDayLimitCategories = passDayLimitCategories;
	}

}
