package in.co.bel.ims.initial.entity;
// Generated 20-Sep-2022, 3:54:24 pm by Hibernate Tools 4.3.5.Final

import java.time.LocalDateTime;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.id.enhanced.SequenceStyleGenerator;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * SessionManagement generated by hbm2java
 */
@Entity
@Table(name = "session_management", schema = "tdms")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class SessionManagement implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private LocalDateTime invalidatedOn;
	private String token;
	private boolean valid = true;
	private boolean deleted;

	public SessionManagement() {
	}

	public SessionManagement(int id, boolean valid) {
		this.id = id;
		this.valid = valid;
	}

	public SessionManagement(int id, LocalDateTime invalidatedOn, String token, boolean valid) {
		this.id = id;
		this.invalidatedOn = invalidatedOn;
		this.token = token;
		this.valid = valid;
	}

	@Id
	@GenericGenerator(name = "sequencePerEntityGenerator", strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator", parameters = {
			@Parameter(name = "prefer_sequence_per_entity", value = "true"),
			@Parameter(name = "initial_value", value = "1"),
			@Parameter(name = SequenceStyleGenerator.INCREMENT_PARAM, value = "1") })
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "sequencePerEntityGenerator")

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	
	@Column(name = "invalidated_on", length = 29)
	public LocalDateTime getInvalidatedOn() {
		return this.invalidatedOn;
	}

	public void setInvalidatedOn(LocalDateTime invalidatedOn) {
		this.invalidatedOn = invalidatedOn;
	}

	@Column(name = "token", length = 500)
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	@Column(name = "valid", nullable = false)
	public boolean isValid() {
		return this.valid;
	}

	public void setValid(boolean valid) {
		this.valid = valid;
	}
	
	@Column(name = "deleted", nullable = false)
	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) { 	 this.deleted = deleted;
		
	}


}
